### ISSUE TITLE
Fatal js-error in publish-panel for unpublished article

### ISSUE THREAD

**Issue by antonborgstrom** [superdesk/superdesk-publisher#347]
When opening the publish-panel for an unpublished article, the page crash with the following error in console:
`angular.js:14800 TypeError: Cannot read properties of undefined (reading 'hidden')
    at t.render (Switch.js:71:30)
    at Fn (react-dom.production.min.js:173:192)
    at Rn (react-dom.production.min.js:172:282)
    at Bl (react-dom.production.min.js:247:361)
    at Er (react-dom.production.min.js:216:164)
    at br (react-dom.production.min.js:210:471)
    at pr (react-dom.production.min.js:206:372)
    at react-dom.production.min.js:114:115
    at t.unstable_runWithPriority (scheduler.production.min.js:20:134)
    at St (react-dom.production.min.js:113:325)
    at Pt (react-dom.production.min.js:114:61)
    at Tt (react-dom.production.min.js:113:476)
    at ur (react-dom.production.min.js:204:235)
    at Object.enqueueSetState (react-dom.production.min.js:127:237)
    at i.setState (react.production.min.js:13:231)
    at PublishPane.jsx:69:23 'Possibly unhandled rejection: {}'`

The error is traced back to Switch.js:71:30 in webpack:///node_modules/superdesk-ui-framework/react/components/Switch.js

**Comment by IvanJelicSF** [comment]
Hey there @antonborgstrom, thanks for the feedback! Can you please share versions for both Superdesk and Superdesk Publisher plugin you are using, as we can't reproduce this on our instances? Thanks!
